services:
  postgres:
    image: postgres:16-alpine
    container_name: nine-universe-db
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: "p@ss"
    ports:
      - "5432:5432"
    volumes:
      - nine-universe-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springuser -d springdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: nine-universe-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springdb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: "p@ss"
    ports:
      - "8080:8080"

volumes:
  nine-universe-pgdata:
